create or replace
PROCEDURE
PROC_NEW_CUSTOMER 	(CUSTOMER_ID OUT INT,
			EMAIL IN VARCHAR,
			FIRSTNAME IN VARCHAR,
			LASTNAME IN VARCHAR,
			GENDER IN VARCHAR,
			BIRTHDATE IN DATE,
			CREDITS IN OUT DECIMAL) IS
BEGIN
	CUSTOMER_ID := SEQUENCE_CUSTOMER_ID.nextval;

	IF CREDITS is NULL THEN
		CREDITS := 10;
	END IF;
	
	INSERT INTO CUSTOMER VALUES(CUSTOMER_ID, EMAIL, FIRSTNAME, LASTNAME, GENDER, BIRTHDATE, CREDITS);
END PROC_NEW_CUSTOMER;